apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: simple-todo-app-kustomize
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: simple-todo-app-source
  interval: 2m
  path: ./simple-todo-app/manifests
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
